2024-01-18 meeting page
SheffieldR/SheffieldR.github.io pull request #18
Opened 2023-12-12 21:19 UTC by ns-rse

First draft of the 2024-01-18 page.

2023-12-13 14:23 UTC, tdjames1 requested changes
Hi @ns-rse, just picking up a couple of minor typos here.

2023-12-13 14:23 UTC, tdjames1 commented on posts/2024-01-18-jan-meetup/index.qmd
> +Meeting is 2024-01-08 17:00-18:30 in The Diamond G04 Workroom 1. Sign up
Correct date:

```suggestion
Meeting is 2024-01-18 17:00-18:30 in The Diamond G04 Workroom 1. Sign up
```

N.B. This needs to be fixed on the Meetup event, too.

2023-12-13 14:23 UTC, tdjames1 commented on posts/2024-01-18-jan-meetup/index.qmd
> +If you have any questions or inquires please get in touch with [Grace Accad](mailto:g.accad@sheffield.ac.uk) or [Neil
Amend spelling and correct typo:
```suggestion
If you have any questions or enquiries please get in touch with [Grace Accad](mailto:g.accad@sheffield.ac.uk) or [Neil
```

2023-12-13 14:23 UTC, tdjames1 commented on posts/2024-01-18-jan-meetup/index.qmd
> +Shephard](mailto:n.shephard@sheffield.ac.uk)/
Correct punctuation:
```suggestion
Shephard](mailto:n.shephard@sheffield.ac.uk).
```

2023-12-14 10:04 UTC, ns-rse commented
Thanks @tdjames1 for the attentive eye for detail, pretty shoddy I mis-typed the date!

2023-12-14 10:15 UTC, tdjames1 approved these changes
Looking good now. I have updated the date on the meetup event blurb!

2023-12-14 11:16 UTC, merged