adding June meetup
SheffieldR/SheffieldR.github.io pull request #45
Opened 2024-05-28 09:21 UTC by G-Accad

2024-05-28 09:59 UTC, tdjames1 requested changes
Thanks @G-Accad! Looks good, just need to fix the time in the yaml header.

2024-05-28 09:59 UTC, tdjames1 commented on posts/2024-06-21-june-meetup/index.qmd
> +date:   2024-06-21 12:00:00 +0000
Time doesn't match description below.

2024-05-28 11:02 UTC, G-Accad commented on posts/2024-06-21-june-meetup/index.qmd
> +date:   2024-06-21 12:00:00 +0000
Thank you!

2024-05-28 16:44 UTC, ns-rse requested changes
Thanks for sorting this out @G-Accad :+1: 

Couple of minor suggestions if you think they are useful but otherwise ready to merge.

2024-05-28 16:44 UTC, ns-rse commented on posts/2024-06-21-june-meetup/index.qmd
> +If you have a fascinating R project you're working on, a useful package you can't live without, or a data analysis technique you think others should know about sign up to present a lightning talk and
Could also add a link to the form here (have wrapped line at 120 as [`markdonwlint-cli2`](https://github.com/DavidAnson/markdownlint-cli2) is failing on pre-commit.ci here and a few other places, but these are minor and aren't a barrier to merging).

```suggestion
If you have a fascinating R project you're working on, a useful package you can't live without, or a data analysis
technique you think others should know about [sign up](https://forms.gle/YSWXarhwUpXZQp2J6) to present a lightning talk
and share it with the SheffieldR community!
```

2024-05-28 16:44 UTC, ns-rse commented on posts/2024-06-21-june-meetup/index.qmd
> +After the event, join us for drinks at the The University Arms pub, it's a great opportunity to continue the conversation, network, and relax with fellow R enthusiasts.
Adding link to University Arms on OpenStreetMap to help people find it (although I expect most to wander from Hicks straight there but you never know some later arrivals might just want to head to the pub!).

```suggestion
After the event, join us for drinks at the [The University Arms pub](https://www.openstreetmap.org/way/178278884), it's
a great opportunity to continue the conversation, network, and relax with fellow R enthusiasts.
```

2024-05-28 16:44 UTC, ns-rse commented on posts/2024-06-21-june-meetup/index.qmd
> +
Normally the `<!--more-->` excerpt_separator would go after the first paragraph separating the overview from the body of the text. It means that only what comes before is summarised on the front page.

Very minor though and not something that needs changing.

2024-05-29 08:36 UTC, ns-rse approved these changes
Thanks for making those changes @G-Accad this is good to go.

Let me know if you'd like assistance with the advertising (can certainly do listing on OSC Sheffield).

2024-05-30 07:48 UTC, merged